package Lox;

 public enum TokenType {
    LEFT_PAREN,
    RIGHT_PAREN,
    LEFT_BRACE,
    RIGHT_BRACE,
    COMMA,DOT,MINUS, SLASH,STAR, PLUS,SEMICOLON,
    RETURN,FALSE,TRUE,
    BANG,BANG_EQUAL,
    EQUAL,EQUAL_EQUAL,
    LESS,LESS_EQUAL,
    GREATER, GREATER_EQUAL,

    IDENTIFIER,STRING,
    NUMBER,

    //KEYWORDS
    AND,OR,ELSE,IF,FOR,CLASS,FUN,NIL,PRINT,SUPER,THIS,VAR,WHILE,
    EOF

}
